# Generated by Django 4.1.7 on 2023-03-17 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Order', models.IntegerField()),
                ('Course', models.CharField(max_length=10)),
                ('Std_no', models.IntegerField()),
                ('Std_name', models.CharField(max_length=30)),
                ('Std_state', models.CharField(max_length=15)),
                ('End_year', models.PositiveIntegerField(null=True)),
                ('Std_plan', models.CharField(max_length=20)),
                ('Prof_main', models.CharField(blank=True, max_length=30)),
                ('Prof_Sec', models.CharField(blank=True, max_length=30)),
                ('Work_name', models.CharField(max_length=200)),
                ('Publish_type', models.CharField(max_length=30)),
                ('Journal_db', models.CharField(blank=True, max_length=30)),
                ('Implementation', models.CharField(blank=True, max_length=40)),
                ('Journal_name', models.CharField(max_length=300)),
                ('Date_start', models.DateField(null=True)),
                ('Date_End', models.DateField(null=True)),
                ('Cal_year', models.PositiveIntegerField(null=True)),
            ],
        ),
    ]
